-

diff --git a/fish/napnap b/fish/napnap
--- a/fish/napnap
+++ b/fish/napnap
@@ -6,13 +6,31 @@ function rnds
     echo $mdir/$a
 end
 
-echo "start recording"
-raspivid -o ~/capture/(date -Is)_napnap.avi -w 640 -h 480 -fps 2 -b 40000 -t 0 &;
+
+set short false
+switch $argv[1]
+    case short
+        set short true
+    case '*'
+        echo "Invalid arg"
+        exit 1
+end
+
+
+
+echo $short NOT WORKING
 
 alarm-timer -m 22; 
-mpv (rnds) --end 10 --volume 60
-alarm-timer -h 1; 
-lightctl f1;
+if $short
+    mpv (rnds)
+    lightctl f1
+else
+    mpv (rnds) --end 10
+end
+
+alarm-timer -h 1
+lightctl f1
+
 alarm-timer -m 8 --em "" --im ""
 mpv (rnds)
 
