add optios to vad; better arg parsing for process conversations

diff --git a/fish/process-conversations b/fish/process-conversations
--- a/fish/process-conversations
+++ b/fish/process-conversations
@@ -23,34 +23,47 @@ set noise_filter_model_path "/home/johannes/rnnoise-models/beguiling-drafter-201
 # - ffmpeg
 # - ffmpeg-normalize
 # - auto-editor
-# - get-speech-timestamps, this script is located in this repo
+# - vad, this script is located in this repo
 
-argparse 'h/help' 'y/yes' 'silent_speed=' 'youtube_prep' 'cut' 'device_index=' 'compute_type=' -- $argv || exit 1
+argparse 'h/help' 'y/yes' 'silent_speed=' 'youtube_prep' 'cut' 'device_index=' 'compute_type=' 'keep_intermediate' 'threshold=' -- $argv || exit 1
+
+set SILENT_SPEED_DEFAULT 6
+set THRESHOLD_DEFAULT 0.25
+set COMPUTE_TYPE_DEFAULT auto
+set DEVICE_INDEX_DEFAULT 0
 
 function help
     set name (basename (status filename))
-    echo "--help -h             Print this help."
-    echo "--yes  -y             Don't prompt for confirmation."
-    echo "--silent_speed FLOAT  How fast to play silent parts [defalut: 6]"
-    echo "--youtube_prep        Prepare a baked subtitle file, and a .vtt"
-    echo "                      transcript without highlighting."
-    echo "--cut                 Cut out the silent parts instead of speeding"
-    echo "                      them up."
-    echo "--device_index        The GPU device index that whisper should"
-    echo "                      use. [default: 0]"
-    echo "--compute_type        The compute type whisper should use. [default: auto]"
+    echo "usage:"
+    echo "  $name [OPTIONS] [FILES]"
+    echo "Options:"
+    echo "  --help -h             Print this help."
+    echo "  --yes  -y             Don't prompt for confirmation."
+    echo "  --silent_speed FLOAT  How fast to play silent parts [defalut: $SILENT_SPEED_DEFAULT]"
+    echo "  --youtube_prep        Prepare a baked subtitle file, and a .vtt"
+    echo "                        transcript without highlighting."
+    echo "  --cut                 Cut out the silent parts instead of speeding"
+    echo "                        them up."
+    echo "  --device_index        The GPU device index that whisper should"
+    echo "                        use. [default: $DEVICE_INDEX_DEFAULT]"
+    echo "  --compute_type        The compute type whisper should use. [default: $COMPUTE_TYPE_DEFAULT]"
+    echo "  --keep_intermediate   Don't delete the TMP folder (useful for debugging)."
+    echo "  --theshold            The threshold for the VAD probability to count as speech. [default: $THRESHOLD_DEFAULT]"
     exit 0
 end
 
 # Setting defaults
 if [ -z "$_flag_silent_speed" ]
-    set _flag_silent_speed 6
+    set _flag_silent_speed "$SILENT_SPEED_DEFAULT"
 end
 if [ -z "$_flag_compute_type" ]
-    set _flag_compute_type "auto"
+    set _flag_compute_type "$COMPUTE_TYPE_DEFAULT"
 end
 if [ -z "$_flag_device_index" ]
-    set _flag_device_index 0
+    set _flag_device_index "$DEVICE_INDEX_DEFAULT"
+end
+if [ -z "$_flag_threshold" ]
+    set _flag_threshold "$THRESHOLD_DEFAULT"
 end
 
 # Further argument handeling
@@ -70,21 +83,40 @@ function trim_ext
     end
 end
 
-# Select files that we want to process
-set target_files (find . -name '*.mkv' -not -name '*_FIN.mkv' -not -name '*_FIN_BAKED.mkv' -not -path '*/TMP/*' | sort --reverse)
+function find-files-recursively
+    set target_files (find . -name '*.mkv' -not -name '*_FIN.mkv' -not -name '*_FIN_BAKED.mkv' -not -path '*/TMP/*' | sort --reverse)
 
-# Filter the files to ignore already processed files.
-for file in $target_files
-    set base_path (trim_ext "$file")
-    set out_file "$base_path"_FIN.mkv
-    if  [ -f "$out_file" ]
-	# echo "For this file there is already a subed file: $file"
-        continue
+    # Filter the files to ignore already processed files.
+    for file in $target_files
+        set base_path (trim_ext "$file")
+        set out_file "$base_path"_FIN.mkv
+        if  [ -f "$out_file" ]
+            # echo "For this file there is already a subed file: $file"
+            continue
+        end
+        set -p filtered_target_files "$file"
     end
-    set -p filtered_target_files "$file"
+
+    for f in $filtered_target_files
+        echo "$f"
+    end
 end
 
-set target_files $filtered_target_files
+# Select files that we want to process
+if [ -n "$argv" ]
+    set target_files $argv
+else
+    echo "Searching for files"
+    set target_files (find-files-recursively)
+end
+
+# Validate
+for f in $target_files
+    if ! [ -f $f ]
+        echo "ERROR: this file does not exsist: $f"
+        exit 1
+    end
+end
 
 # Let user confirm targeted Files
 echo "Target Files:"
@@ -111,6 +143,14 @@ for file in $target_files
     set subs_dir_2 "$tmp_dir"/SUBS_2
     set vf_baked_file (trim_ext "$out_file")_BAKED.mkv
 
+    if [ -d "$tmp_dir" ]
+        echo "WARNING already exists: $tmp_dir"
+        if [ -z "$_flag_yes" ]
+            read -p "echo PESS ENTER to DELETE and continue"
+        end
+        rm -r "$tmp_dir"
+    end
+
     mkdir "$tmp_dir" || exit 1
 
     echo -e "\nNormalizing Audio"
@@ -121,7 +161,7 @@ for file in $target_files
 
     echo -e "\nCutting video File"
     begin
-        get-speech-timestamps "$denoised_file" | xargs auto-editor --margin 0,0.1s "$denoised_file" --silent_speed "$_flag_silent_speed" --video-bitrate unset --no-open --output "$cut_file" --mark-as-loud
+        vad timestamps "$denoised_file" --threshold "$_flag_threshold" | xargs auto-editor --margin 0.2s,0.2s "$denoised_file" --silent_speed "$_flag_silent_speed" --video-bitrate unset --no-open --output "$cut_file" --mark-as-loud
     end || exit 1
 
     echo -e "\nGenerate transcript"
@@ -147,5 +187,7 @@ for file in $target_files
     end
 
     # Cleanup
-    rm -r "$tmp_dir" || exit 1
+    if [ -z "$_flag_keep_intermediate" ]
+        rm -r "$tmp_dir" || exit 1
+    end
 end
