-

diff --git a/fish/wacom-setup b/fish/wacom-setup
--- a/fish/wacom-setup
+++ b/fish/wacom-setup
@@ -8,7 +8,7 @@ function button-map
     echo $argv[1]
   else if [ $argv[1] -lt 13 ]
     echo (math "$argv[1] + 4")
-  else 
+  else
     echo There are only buttons 1-8. Invalid button: $argv[1]
     exit 1
   end
@@ -63,13 +63,33 @@ function krita-vert
     xsetwacom set "$pad_id" button (button-map 8) "key ctrl shift a"
 end
 
-switch $argv[1]
-  case miro
-    miro
-  case krita
-    krita
-  case krita-vert
-      krita-vert
-  case '*'
-    echo "invalid config"
+function SynthV
+    xsetwacom set "$pen_id" maptooutput "HEAD-2"
+    xsetwacom set "$pen_id" area 0 0 55200 31050
+
+    xsetwacom set "$pen_id" button 3 "3"
+
+    xsetwacom set "$pad_id" button (button-map 1) "key ctrl z"
+    xsetwacom set "$pad_id" button (button-map 2) "key ctrl shift z"
+    xsetwacom set "$pad_id" button (button-map 3) "key ctrl c"
+    xsetwacom set "$pad_id" button (button-map 4) "key ctrl v"
+    xsetwacom set "$pad_id" button (button-map 5) "key b"
+    xsetwacom set "$pad_id" button (button-map 6) "key t"
+    xsetwacom set "$pad_id" button (button-map 7) "key ctrl r"
+    xsetwacom set "$pad_id" button (button-map 8) "key ctrl shift a"
 end
+
+if not eval $argv[1]
+    exit 1
+end
+
+# switch $argv[1]
+#   case miro
+#     miro
+#   case krita
+#     krita
+#   case krita-vert
+#       krita-vert
+#   case '*'
+#     echo "invalid config"
+# end
